POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9ybGFuZG90aGVicmFuZG8iLCJpZCI6IjVlM2M4Y2RiNDVhZjIzMjZjODY2YmQ4MSIsImlhdCI6MTU4MTAyNjU1N30.xDepFAGzQdTGs9jFLgSrzFwAfHGoj8N-v2kGTBiLIKY

{
    "title": "10 Awesome Ways to Photograph Butterflies",
    "author": "Emillie Owens",
    "url": "https://SiestaMailedLintel.com",
    "likes": 36
}